name: Java CI with Gradle

on:
  push:
    branches: [ "feat/cicd" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean test bootJar jacocoTestCoverageVerification bootJar

      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/chill-container .

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/chill-container

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      - name: Docker pull
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/chill-container

      - name: Stop and remove existing containers
        run: |
          CONTAINER_IDS=$(sudo docker ps -aq --filter "name=chill-container")
          if [ -n "$CONTAINER_IDS" ]; then
            sudo docker stop $CONTAINER_IDS || true
            sudo docker rm -f $CONTAINER_IDS || true
          fi

      - name: Create .env file
        run: |
          echo "${{ secrets.APPLICATION }}" > .env

      - name: Run new container
        run: |
          sudo docker run --name chill-container -d \
            --env-file .env \
            -p 8080:8080 \
            ${{ secrets.DOCKER_USERNAME }}/chill-container
